services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: make dev
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
  
  caddy:
    image: caddy:2.9.1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app