services:
  app:
    build:
      context: ./app
      dockerfile: ../Dockerfile
    command: make dev
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
  
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./app/services/caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config: