services:
  app:
    build:
      dockerfile: Dockerfile
    command: make dev
    volumes:
      - .:/app
    ports:
      - "8080:8080"
  
  caddy:
    image: caddy:2.9
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./services/caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config: